NAVER_CLIENT_ID=o8zoNVtIk7BfxmdeHtU3
NAVER_CLIENT_SECRET=C0fwsH6Ljc
GEMINI_API_KEY=AIzaSyChLbC_TPFwTt5I9Ub20ikX1Ok4Ughrqb0
NAVER_AD_API_KEY=0100000000e822e02aa8ae50000822fcc103e19046f61c81de472b854c4e290991c27f5bdf
NAVER_AD_SECRET_KEY=AQAAAADoIuAqqK5QAAgi/MED4ZBGduKs4YvCgLkVYZaFXJ4AsA==
NAVER_AD_CUSTOMER_ID=2463922